# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46ced128378bf06166c714511a4a95a75a2d554cb71630012f0039eb8d6c7cc1b693ecc23df9295f96dbd800aa8615b93c9c4e252dc32368eac4d026e309fac4

test:
  secret_key_base: 49cb7365c7f26b07fe9794f1fa8fe9a11769aed187ebeccd42fada1442d93138f4f81d16f1b2a0454dd0683598b08b938933d5722f0cd15c3108831a5797bf88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
